const actionTypes = {
    /* PRODUCT ACTIONS START */
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',
    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAIL: 'PRODUCT_CREATE_FAIL',
    /* PRODUCT ACTIONS END */
    /* USER ACTIONS START */
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
    /* USER ACTIONS END */
};

export default actionTypes;